- schema/ext/vulnerability-1.0.xsd
Adding a draft software vulnerability schema for discussion and getting feedback.
Note: the descriptions are not final and to be updated later on, upon structure finalization.
References: https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/schema/dependency-check.2.2.xsd
> Draft vulnerability schema extension

- schema/bom-1.3-SNAPSHOT.schema.json
- schema/bom-1.3-SNAPSHOT.xsd
Follow-on from #57, which on balance seems like a bad idea.
This just fixes the descriptive text part for 1.3 schemas, which should be a compatible change.
> manufacture grammar fix

- schema/bom-1.3-SNAPSHOT.schema.json
- schema/bom-1.3-SNAPSHOT.xsd
Should not be any material change. Just removing duplicate definitions.
> Refactor BOM license to make use of license choice type

- schema/bom-1.3-SNAPSHOT-strict.schema.json
- schema/bom-1.3-SNAPSHOT.schema.json
Ensure consistency for all URI/URLs to be defined as strings that must conform to the iri-reference format.
> URI cleanup for JSON

- schema/bom-1.2-strict.schema.json
- schema/bom-1.3-strict.schema.json
> JSON strict: add optional root property `$schema`

- schema/bom-1.4-SNAPSHOT.schema.json
part of #83 for spec 1.4 
* removed duplicate `$id` definitions
* removed all `$id` markers (the ones that were just json-pointers prefixed with `#` and all the others that were not used internally)
> spec1.4 JSON fixes #83

- schema/bom-1.4-SNAPSHOT.schema.json
> spec 1.4 JSON schema: remove unnecessary self-shadowing `$id`

- schema/bom-1.4-SNAPSHOT.proto
This was missing from the proto file, but is present in JSON and XML schemas.
> Add service release notes to v1.4 proto file

- .github/workflows/php.yml
- tools/src/test/php/README.md
- tools/src/test/php/composer.json
- tools/src/test/php/json-schema-lint-tests.php
part of #86 for #123
* added the existing php tests as a GitHub workflow
* slight fixes and extensibility-modifications to existing php test-setup
:point_up:  PHP CI is currently failing, since some JSON schema files are not entirely valid/plausible - which is topic of #83/#123
this might be fixed via (#84/#125/...) - #124
as soon as the JSON schema files were fixed, they will pass.
Then these test can act as a gatekeeper.
> add GH-workflow: php ci

- tools/src/test/resources/1.4/valid-vulnerability-1.4.json
1. The vulnerability use a reference to a component that is not in the BOM.
Should be `pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.9.4`
instead of `pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.9.9`
Because the firs tone is in the bom-ref of a component in the BOM.
See [tools/src/test/resources/1.4/valid-vulnerability-1.4.json](../blob/master/tools/src/test/resources/1.4/valid-vulnerability-1.4.json#L103)
2. the CVSS v3 vector is wrong (not well formed data)
It is `"vector": "AN/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",` in the current file.
Should be `"vector": "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",`
> Fix invalid ref in tools/src/test/resources/1.4/valid-vulnerability-1.4.json

- schema/bom-1.4.proto
- schema/bom-1.4.xsd
- tools/src/test/resources/1.4/valid-vulnerability-1.4.json
- tools/src/test/resources/1.4/valid-vulnerability-1.4.textproto
- tools/src/test/resources/1.4/valid-vulnerability-1.4.xml
Closes https://github.com/CycloneDX/specification/issues/147
> fix: add missing `Vulnerability.properties` types in schema 1.4

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-vulnerability-1.5.json
- tools/src/test/resources/1.5/valid-vulnerability-1.5.textproto
- tools/src/test/resources/1.5/valid-vulnerability-1.5.xml
Closes #142 and implements 0.9 draft of CISA VEX requirements
> Added firstIssued and lastUpdated timestamps to vulnerability analysis

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-properties-1.5.json
- tools/src/test/resources/1.5/valid-properties-1.5.textproto
- tools/src/test/resources/1.5/valid-properties-1.5.xml
> Added property support to license along with unit tests

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-saasbom-1.5.json
- tools/src/test/resources/1.5/valid-saasbom-1.5.textproto
- tools/src/test/resources/1.5/valid-saasbom-1.5.xml
Expanded service dataflow support. Closes #191
> Extend service dataflow support

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-metadata-tool-1.5.json
- tools/src/test/resources/1.5/valid-metadata-tool-1.5.textproto
- tools/src/test/resources/1.5/valid-metadata-tool-1.5.xml
- tools/src/test/resources/1.5/valid-metadata-tool-deprecated-1.5.json
- tools/src/test/resources/1.5/valid-metadata-tool-deprecated-1.5.textproto
- tools/src/test/resources/1.5/valid-metadata-tool-deprecated-1.5.xml
- tools/src/test/resources/1.5/valid-vulnerability-1.5.json
- tools/src/test/resources/1.5/valid-vulnerability-1.5.textproto
- tools/src/test/resources/1.5/valid-vulnerability-1.5.xml
Deprecated tool in favor of components and services used as tools. Added both current 1.5 and deprecated examples of each.
Closes #196
> Deprecated tool in favor of components and services used as tools

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-evidence-1.5.json
- tools/src/test/resources/1.5/valid-evidence-1.5.textproto
- tools/src/test/resources/1.5/valid-evidence-1.5.xml
> Added identity and occurrences to evidence. Updated test cases.

- schema/bom-1.4.schema.json
i found `vulnerability.affects[].versions[].range` wrong. it pointed to `version`, not `range`.
this is to be considered a non-braking change.
actually it does not affect any documents, since the old ref and the fixed ref point to equal data structures.
> fix `vulnerability.affects[].versions[].range` ref

- schema/bom-1.4.xsd
fixes #182
The `bom:refType` is just an alias of `xs:string` with an annotation.
Therefore, I propose to merge this without any version bump.
> fix: XML schema 1.4 make all `ref` arguments `type="bom:refType"`

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-saasbom-1.5.json
- tools/src/test/resources/1.5/valid-saasbom-1.5.textproto
- tools/src/test/resources/1.5/valid-saasbom-1.5.xml
Data governance was added as part of ML support, however, governance should have been applied to #194 but was missed. This PR corrects that oversight.
> Fixing missing data governance on service data

- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
caused by #217 
Introduction of `bomLink` types,
so that they can be used where needed, later.
This should allow formulating the answer for #136 and #217 in the schema,
so that there would be clarity.
> Introduce type for BOM-Link

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-metadata-manufacture-1.5.json
- tools/src/test/resources/1.5/valid-metadata-manufacture-1.5.textproto
- tools/src/test/resources/1.5/valid-metadata-manufacture-1.5.xml
- tools/src/test/resources/1.5/valid-metadata-supplier-1.5.json
- tools/src/test/resources/1.5/valid-metadata-supplier-1.5.textproto
- tools/src/test/resources/1.5/valid-metadata-supplier-1.5.xml
> Added bom-refs to organizationalEntity and organizationalContact

- tools/src/test/php/composer.json
continues from by #237 
some tests fail due to to-be-fixed example files.
> v1.5 validate XML/JSON test-data against schema - php

- tools/src/test/js/README.md
- tools/src/test/js/json-schema-functional-tests.js
- tools/src/test/js/json-schema-lint-tests.js
- tools/src/test/js/package.json
yet another json schema runner, that validates the [exiting test data](https://github.com/CycloneDX/specification/tree/v1.5-dev/tools/src/test/resources).
here `AJV` is used to validate json. it is yet another implementation of json schema.
one that might be more or less strict to the standards.
I left out the XML validation, because we already have one that utilizes `libxml2` - the PHP does that.
similar to #238
> validate JSON test data against schema - JS

- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
@mrutkows could you help improve the schema in terms of documentation? 
the `resourceReferenceChoice.ref` is intended to link to a `bom-ref`.
Question: Must this link to a `bom-ref` in the **same** document, or would it also be okay to link to a `bom-ref` in **another** document aswell, using a [BOM-Link](https://cyclonedx.org/capabilities/bomlink/)? 
depending on your answer, I might need to modify the content of this PR.
see comments below ...
----
there was some documentation enhancement brought into the schema to make this much clearer.
followup of #236 & #222
caused by #136 and #217
> V1.5 dev resourceReferenceChoice ref clarifications

- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- tools/src/test/resources/1.5/valid-license-expression-1.5.json
- tools/src/test/resources/1.5/valid-license-expression-1.5.xml
- tools/src/test/resources/1.5/valid-license-id-1.5.json
- tools/src/test/resources/1.5/valid-license-id-1.5.xml
- tools/src/test/resources/1.5/valid-license-name-1.5.json
- tools/src/test/resources/1.5/valid-license-name-1.5.xml
currently, all named- and SPDX-licenses were linkable, as they had a bom-ref.
the SPDX licen expression did not have one, yet.
to  make it linkable (in licensing-docs), it is needed to add a `bom-ref` to the license expression, too. 
- add examples for licenses with links
- add `bom-ref` to license expressions, so ALL licenses are linkable
> v1.5 complete linkable licenses

- schema/bom-1.5.proto
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
fixes #78
see #216
----- 
* Proto
* document the defaults that are already formulated in XML and JSON
* JSON 
* `bom.version` is no longer required. it already has a default value to which it falls back if omitted. 
it already is optional in XML.
see #78
* XML
* `component.scope` now defaults to `required`
* already documented to fall back to value `required` in XML
* in JSON it has a default of `required` already
> adjust default values

- tools/src/test/resources/1.2/valid-service-1.2.json
- tools/src/test/resources/1.3/valid-service-1.3.json
- tools/src/test/resources/1.3/valid-service-1.3.textproto
- tools/src/test/resources/1.4/valid-service-1.4.json
- tools/src/test/resources/1.4/valid-service-1.4.textproto
- tools/src/test/resources/1.5/valid-service-1.5.json
- tools/src/test/resources/1.5/valid-service-1.5.textproto
Fixes an inconsistency in test data of valid-service. First experienced in valid-service-1.4.json, other files (other versions and filetypes) showed the same deviation. The fix was derived from working test data of valid-service.
closes #294
> Fix test data, closes #294

- CODEOWNERS
in the past i set the `reviewers` manually.
i want this to be automated... so here is a technical solution that works for github.
> chore: add `@CycloneDX/core-team` as default reviewers

- tools/src/test/resources/1.3/valid-compositions-1.3.json
- tools/src/test/resources/1.3/valid-compositions-1.3.textproto
- tools/src/test/resources/1.4/valid-compositions-1.4.json
- tools/src/test/resources/1.4/valid-compositions-1.4.textproto
- tools/src/test/resources/1.5/valid-compositions-1.5.json
- tools/src/test/resources/1.5/valid-compositions-1.5.textproto
> Fix `bom-ref` in test data `valid-compositions`

- schema/bom-1.6.schema.json
This PR follows our CBOM WG call from Oct 12. It removes the `detectionContext` property from components and merges them with `componentEvidence`. The following properties are added to evidence:
- `lineNumber`
- `offset`
- `symbol`
- `additionalContext`
The plan is to make a separate proposal/PR for `keyword`
The PR also removes the extra fields for confidence levels since they are already covered by `componentEvidence`.
Tagging @stevespringett @n1ckl0sk0rtge @mrutkows
> Merges detectionContext properties with component evidence

- schema/bom-1.6.schema.json
This addresses the use case described in https://github.com/IBM/CBOM/issues/31:
- Expiry and life cycle of any relatedCryptoMaterial (e.g. keys, tokens, password) should be expressible.
This is done by merging the "key" asset type and "relatedCryptoMaterial" to "relatedCryptoMaterial", which contains the needed properties.
> CBOM: merges relatedCryptoMaterial and key asset types

- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
goal: improve documentation by consolidating elements regarding "version".
pure refactoring, no new functionality was added, nor removed, nor changed.
> refactor: centralize version and version-range

- schema/bom-1.6.schema.json
Move comment in `$comment` to description for increased visibility.
Closes: https://github.com/CycloneDX/specification/issues/336
> Move comment to description

- schema/bom-1.6.schema.json
Reviews the description fields and addresses my TODOs.
> Review description fields of 'algorithmProperties'

- schema/bom-1.6.schema.json
Adds 'combiner' as enum entry in 'primitive'.
Addresses the use case when combinations of (e.g.) classical crypto like RSA is used together with QSC like Dilithium. An entry of this primitive allows to express the combiner used. Adding dependencies to RSA/Dilithium then allows to express the algorithms used in the combiner. Note: "combiners" are also known as "hybrids", but this term can be ambiguous so I prefer the term combiner.
> Support for hybrids/combiners: add 'combiner' as primitive

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
- tools/src/test/resources/1.6/valid-cryptography-implementation-1.6.json
- tools/src/test/resources/1.6/valid-cryptography-implementation-1.6.textproto
- tools/src/test/resources/1.6/valid-cryptography-implementation-1.6.xml
changes as discussed here: https://github.com/CycloneDX/specification/pull/347#discussion_r1466522226
> rework dependency type to `provides`

- schema/bom-1.6.schema.json
- tools/src/test/resources/1.6/invalid-properties-1.6.json
- tools/src/test/resources/1.6/invalid-properties-1.6.textproto
- tools/src/test/resources/1.6/invalid-properties-1.6.xml
- tools/src/test/resources/1.6/valid-properties-1.6.json
- tools/src/test/resources/1.6/valid-properties-1.6.textproto
- tools/src/test/resources/1.6/valid-properties-1.6.xml
> 1.6 dev fix properties json - fixes #371

- schema/bom-1.6.schema.json
Fixes #373 which addresses a small typo in the `counterClaim` field title in the Attestation 1.6
> fix: correcting title of `attestations[].map[].counterClaim`

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
> Add  `meta:enum` descriptions for task types

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
fixes https://github.com/CycloneDX/specification/issues/273
> docs: describe `$.metadata.licenses`

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
fixes https://github.com/CycloneDX/specification/issues/380
> feat: external reference type for RFC-9116

- schema/bom-1.6.proto
- tools/src/test/resources/1.6/valid-metadata-license-1.6.json
- tools/src/test/resources/1.6/valid-metadata-license-1.6.textproto
- tools/src/test/resources/1.6/valid-metadata-license-1.6.xml
> fix: protobuf `Metadata.licenses` repeated

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
> Added descriptions for ML learning types

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
- tools/src/test/resources/1.6/valid-evidence-1.6.json
- tools/src/test/resources/1.6/valid-evidence-1.6.textproto
- tools/src/test/resources/1.6/valid-evidence-1.6.xml
> Added support for concluded value. Updated test cases.

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
- tools/src/test/resources/1.6/valid-license-expression-1.6.json
- tools/src/test/resources/1.6/valid-license-expression-1.6.textproto
- tools/src/test/resources/1.6/valid-license-expression-1.6.xml
- tools/src/test/resources/1.6/valid-license-id-1.6.json
- tools/src/test/resources/1.6/valid-license-id-1.6.textproto
- tools/src/test/resources/1.6/valid-license-id-1.6.xml
> Added support for license acknowledgements

- schema/bom-1.6.proto
- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
- tools/src/test/resources/1.6/valid-component-identifiers-1.6.json
- tools/src/test/resources/1.6/valid-component-identifiers-1.6.textproto
- tools/src/test/resources/1.6/valid-component-identifiers-1.6.xml
> Add support for OmniBOR and Software Heritage persistent IDs

- schema/bom-1.6.xsd
- tools/src/test/resources/1.6/valid-component-identifiers-1.6.json
- tools/src/test/resources/1.6/valid-component-identifiers-1.6.textproto
- tools/src/test/resources/1.6/valid-component-identifiers-1.6.xml
something was off in the test data - <https://github.com/CycloneDX/specification/actions/runs/8476878829/job/23227006633?pr=323#step:5:874> 
here is the fix
> fix: revisit new component identifiers

- tools/src/test/proto/test.sh
https://github.com/bufbuild/buf/releases/tag/v1.30.1
> Fix issue where `buf lint` incorrectly reports an error for `(buf.validate.field).repeated`
is set for a repeated validation rule.
> chore(dependencies): bump bufbuild/buf:1.30.1

- schema/bom-1.5.proto
- schema/bom-1.6.proto
> docs: annotate protobuf licenses

- tools/src/test/java/org/cyclonedx/schema/BaseSchemaVerificationTest.java
- tools/src/test/java/org/cyclonedx/schema/JsonSchemaVerificationTest.java
- tools/src/test/java/org/cyclonedx/schema/XmlSchemaVerificationTest.java
See related PRs: #480 (and #479).
See below the Java tests seems to run okay:
> tests: Adding 1.6 valid and invalid test files in the Java tests

- schema/bom-1.6.xsd
closes #452
revisited all `https?://` in the current spec. no example domain was used, except the intended `example.com`.
streamlined JSON and XML.
> docs: revisit example urls in spec 1.6

- schema/bom-1.6.schema.json
When trying to create a pydantic class from this spec using `datamodel-code-gen`, having a quote right after a colon creates the following error: https://stackoverflow.com/questions/9055371/python-and-pyaml-yaml-scanner-scannererror-mapping-values-are-not-allowed-her
Adding a space to make this processable by datamodel-code-gen
> Add space after colon

- docgen/xml/gen.sh
according to the [Saxonica](https://www.saxonica.com), the authors of `Saxon HE`, the v9 is no longer maintained. so lets upgrade.
> [...] current actively maintained versions of Saxon-HE: [10](https://github.com/Saxonica/Saxon-HE/blob/main/10), [11](https://github.com/Saxonica/Saxon-HE/blob/main/11), and [12](https://github.com/Saxonica/Saxon-HE/blob/main/12).
tried to upgrade to v12 or v11 without success.
so i chose the latest successful version: v10.9
> chore(dependencies): bump Saxon-HE from 9.9.1-8 to 10.9

- schema/bom-1.6.proto
- schema/bom-1.6.xsd
> fix: add missing cryptoRef to `cryptoProperties.protocolPropertiesfor` XML/PB

- schema/bom-1.6.proto
fixes #422 
and yes, fixing this bug is actually considered a breaking change in terms of ProtoBuf
> fix: ProtoBuf evidence not repeated, but optional

- schema/bom-1.6.proto
non-breaking fix of #422 
in contrast to #425
> fix(ProtoBuff): component evidence should be optional, istead of repeated

- schema/bom-1.6.proto
- tools/src/test/resources/1.6/valid-external-reference-1.6.json
- tools/src/test/resources/1.6/valid-external-reference-1.6.textproto
- tools/src/test/resources/1.6/valid-external-reference-1.6.xml
- tools/src/test/resources/1.6/valid-release-notes-1.6.json
- tools/src/test/resources/1.6/valid-release-notes-1.6.textproto
- tools/src/test/resources/1.6/valid-release-notes-1.6.xml
> fix(ProtoBuf): add ExternalReterence Type `EXTERNAL_REFERENCE_TYPE_RELEASE_NOTES`

- schema/bom-1.6.proto
- schema/bom-1.6.xsd
- tools/src/test/resources/1.6/valid-component-data-1.6.json
- tools/src/test/resources/1.6/valid-component-data-1.6.textproto
- tools/src/test/resources/1.6/valid-component-data-1.6.xml
- tools/src/test/resources/1.6/valid-component-types-1.6.json
- tools/src/test/resources/1.6/valid-component-types-1.6.textproto
- tools/src/test/resources/1.6/valid-component-types-1.6.xml
fixes <https://github.com/CycloneDX/specification/issues/518>
> fix(ProtoBuf,XML): component data repeatable

- schema/bom-1.6.proto
fixes #422 
by reverting the unreleased https://github.com/CycloneDX/specification/commit/19a153072690dfb2e8475ea3fa2e09a657d0cef6  & https://github.com/CycloneDX/specification/commit/acc5f3a003f26a6f165d83e5f4f7706546ccc055
as discussed here: https://github.com/CycloneDX/specification/issues/422#issuecomment-2454961082
> fix(ProtoBuf): `Component.evidence` optional

- schema/bom-1.6.proto
- tools/src/test/resources/1.6/valid-license-expression-1.6.textproto
> fix(ProtoBuf): add `LicenseExpression.bom_ref`

- schema/bom-1.6.proto
- tools/src/test/proto/buf_lint.yaml
fixes #538 
texts were taken from the human-readable Spec CycloneDX 1.6.0
> docs: transfer spec docs to ProtoBuf 1.6

- schema/bom-1.6.xsd
texts were taken from human-readable spec
> docs: transfer specdocs to XML 1.6

- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
> fix: typos in schemas 1.6

- README.md
mimic https://cyclonedx.org/specification/overview/
> docs: Recognized file patterns

- docgen/json/templates/cyclonedx/base.html
- docgen/proto/gen.sh
- docgen/proto/templates/html.tmpl
- docgen/xml/xs3p.xsl
> docs: docsgen theme and linkd for proto

- docgen/json/templates/cyclonedx/base.html
- docgen/proto/templates/html.tmpl
current docsgen result in broken metatags:
```html
<meta name="twitter:title" content=""CycloneDX v1.6 Protobuf Reference""/>
<meta name="twitter:image" content="https://cyclonedx.org/images/CycloneDX-Social-Card.png"/>
<meta name="twitter:description" content=""CycloneDX v1.6 Protobuf Reference""/>
<meta name="description" content=""CycloneDX v1.6 Protobuf Reference""/>
<meta property="og:description" content=""CycloneDX v1.6 Protobuf Reference""/>
<meta property="og:title" content=""CycloneDX v1.6 Protobuf Reference""/>
```
this PR fixes this
> docs: docsge fix title in `<meta>` elements

- .github/pull_request_template.md
when a spec PR pops up without any previous discussion, then this usually disturbs me.
A PR w/o a proper issue means somebody skipped the most relevant part: give people a proper understanding of the "problem" and give them the freedom to think about possible solutions freely. Starting with a solution always narrows the view of everybody, and in almost all cases the proposed solution is not the best one.
to guide pull-requests, i propose the following PR template: https://github.com/CycloneDX/specification/pull/579
What do you think about the situation?
- Should PRs without a ticket exist in our spec-repo?
- What about the wording in the PR template? is it friendly enough to no guide people and not scare them away? 
(Yes, I opened this PR without any discussion/ticket before. Ironic, …
> chore: introduce PR template

- docgen/json/gen.sh
- docgen/proto/gen.sh
- docgen/xml/gen.sh
We often only need the latest docs, while developing a new version.
Therefore, the latest version's docs are generated first.
> docs: docsgen latest first

- schema/xmlcatalog.xml
- tools/pom.xml
- tools/src/test/java/org/cyclonedx/schema/XmlCatalogVerificationTest.java
Adding an XML catalog file and corresponding Java unit tests to validate the XML catalog content match local XSD file content.
Please see also: https://github.com/CycloneDX/specification/pull/477
I needed to modify the `pom.xml` to include the path to the `schema/` folder. This might not be a Java/maven best practice, but given how the folders are organised, I have no other solutions without changing the folders location:
> Access "/home/user/cyclonedx-specification.thalesgroup/tools/../schema" directory outside of project base directory. (org.apache.maven.plugins:maven-resources-plugin:3.3.1:testResources:default-testResources:process-test-resources)
Java unit tests seem okay, see picture below:
```
java  --version
openjdk 22 2024-03-19
OpenJDK Runtime Environment (build 22)
OpenJDK …
```
> feat(DX): add xml catalog for XSD

- tools/pom.xml
- tools/src/test/java/org/cyclonedx/schema/BaseSchemaVerificationTest.java
- tools/src/test/java/org/cyclonedx/schema/JsonSchemaVerificationTest.java
- tools/src/test/java/org/cyclonedx/schema/XmlSchemaVerificationTest.java
This change modifies the Java Unit tests to use the schemas in this repository to validate the examples, instead of those bundled in the `cyclonedx-java-core` artifact.
Closes #256
> tests(Java): run test against actual schema files

- schema/bom-1.7.xsd
Fix missing type definitions for ComponentData subelements
Fixes #600
> Fix missing type definitions for ComponentData subelements in XML

- schema/bom-1.7.schema.json
- schema/cryptography-defs.json
- schema/cryptography-defs.schema.json
- Extends cryptography-defs.json list with algorithms from PKCS11
- Changes schma for crypto-defs to allow different variant patterns corresponding to different primitives
- Adds "key-wrap" as a new primitive
> Extends cryptography-defs.json

- schema/bom-1.7.proto
- schema/bom-1.7.schema.json
- schema/bom-1.7.xsd
- tools/src/test/resources/1.7/valid-external-reference-properties-1.7.json
- tools/src/test/resources/1.7/valid-external-reference-properties-1.7.textproto
- tools/src/test/resources/1.7/valid-external-reference-properties-1.7.xml
With this property external references can be annotated with additional metadata in a machine-readable format.
As discussed in #608 this adds support for custom properties in external references.
fixes #608
> feat: add custom properties to external references 

- schema/cryptography-defs.json
The following rules apply for the patterns:
{placeholder} -> required parameter with placeholder
(option1|option2) -> required parameter with fixed alternatives 
[parameter] -> optional parameter
[-{placeholder}] -> optional parameter with literal separator
> Review algorithm list, apply rules for patterns

- schema/bom-1.7.proto
- schema/bom-1.7.schema.json
- schema/bom-1.7.xsd
- tools/src/test/resources/1.7/invalid-citations-1.7.json
- tools/src/test/resources/1.7/invalid-citations-1.7.textproto
- tools/src/test/resources/1.7/invalid-citations-1.7.xml
- tools/src/test/resources/1.7/valid-citations-1.7.json
- tools/src/test/resources/1.7/valid-citations-1.7.textproto
- tools/src/test/resources/1.7/valid-citations-1.7.xml
on top of #630
changes:
- ADDED: citation's "attributedTo" may also link to tools  -- yes, we have "processes", which are basically tools, but this way it might get more convenient to use citations for BOM generators. 
- DOCS: streamlined documentation
- REFACTOR: reworked the ProtoBuf structures to match some constraints in the the spec -- `choice`/`oneOf` ... 
- TESTS: practical examples for `citation.expressions`
> [1.7] citation:  proposed changes 2

- schema/cryptography-defs.json
This PR further extends the list of algorithms in cryptography-defs.json.
> Extend crypto definitions

- schema/bom-1.7.proto
- schema/bom-1.7.schema.json
- schema/bom-1.7.xsd
- tools/src/test/resources/1.7/valid-metadata-distribution-1.7.json
- tools/src/test/resources/1.7/valid-metadata-distribution-1.7.textproto
- tools/src/test/resources/1.7/valid-metadata-distribution-1.7.xml
Refactored `metadata.distribution` to be more verbose in its name, and made it more versatile by converting it to an "object" with "TLP" as a property.
caused by https://github.com/CycloneDX/specification/pull/603#issuecomment-2972771553
> refactor: metadata distribution to be an object

- schema/bom-1.7.proto
- schema/bom-1.7.schema.json
- schema/bom-1.7.xsd
removed the word "optional" whenever possible, as the schemas clearly tell when something is optional or required.
as agreed in https://github.com/CycloneDX/specification/issues/616#issuecomment-2761792157 and https://github.com/CycloneDX/specification/issues/649#issuecomment-2964680048
- fixes #616
- fixes #649
> fix: remove the word "optional", align some docs

- schema/bom-1.7.proto
- tools/src/test/proto/test.sh
- tools/src/test/resources/1.7/valid-cryptography-full-1.7.textproto
removed breaking changes in Protocol Buffer schema regarding CBOM changes
caused by https://github.com/CycloneDX/specification/pull/657#issuecomment-3244561693
> [1.7] - Updates from CBOM working group - remove any BREAKING CHANGES for ProtoBuf
