CycloneDX/specification

schema/bom-1.3-SNAPSHOT-strict.schema.json
schema/bom-1.3-SNAPSHOT.schema.json
schema/bom-1.3-SNAPSHOT.xsd
tools/src/test/resources/1.3/valid-external-reference-1.3.json
tools/src/test/resources/1.3/valid-external-reference-1.3.xml

Had to redo this PR as the prior one wasn't forked from v1.3, rather another branch causing issues.

#69 - Added support for hashes on external references. Added unit tests

---

schema/bom-1.3-SNAPSHOT-strict.schema.json
schema/bom-1.3-SNAPSHOT.schema.json

Removed default empty string and unnecessary regex pattern that allowed all characters.
Java Core has already been updated with these changes. The checks performed in this PR will be using the modified versions which should validate they work.

Removed default empty string and unnecessary regex pattern

---

schema/bom-1.4-SNAPSHOT.proto
schema/bom-1.4-SNAPSHOT.schema.json
schema/bom-1.4-SNAPSHOT.xsd
schema/bom-1.4-strict-SNAPSHOT.schema.json

Added external references support to tools

---

schema/bom-1.4-SNAPSHOT.proto
schema/bom-1.4-SNAPSHOT.schema.json
schema/bom-1.4-SNAPSHOT.xsd
schema/bom-1.4-strict-SNAPSHOT.schema.json
tools/src/test/resources/1.4/valid-minimal-viable-1.4.json
tools/src/test/resources/1.4/valid-minimal-viable-1.4.textproto
tools/src/test/resources/1.4/valid-minimal-viable-1.4.xml
tools/src/test/resources/1.4/valid-vulnerabilities-1.4.xml

Made component version optional

---

schema/bom-1.4-SNAPSHOT.schema.json
schema/bom-1.4-SNAPSHOT.xsd

schema spec1.4: own type for `ref`/`bom-ref`

---

schema/bom-1.4-SNAPSHOT.schema.json

spec1.4 JSON schema : bugfixes  #83

---

schema/bom-1.4.schema.json

fix CWEs example

---

schema/bom-1.5.proto
schema/bom-1.5.schema.json

Resolves #130 - missing BOM properties in JSON and protobuf schemas

---

schema/bom-1.5.proto
schema/bom-1.5.schema.json
schema/bom-1.5.xsd
tools/src/test/resources/1.5/valid-annotation-1.5.json
tools/src/test/resources/1.5/valid-annotation-1.5.textproto
tools/src/test/resources/1.5/valid-annotation-1.5.xml

Add annotations support and valid test cases

---

schema/bom-1.5.proto
schema/bom-1.5.schema.json
schema/bom-1.5.xsd
tools/src/test/resources/1.5/valid-vulnerability-1.5.json
tools/src/test/resources/1.5/valid-vulnerability-1.5.textproto
tools/src/test/resources/1.5/valid-vulnerability-1.5.xml

Adding support vulnerability rejected timestamp along with unit tests

---

schema/bom-1.5.proto
schema/bom-1.5.schema.json
schema/bom-1.5.xsd

Added support for CVSSv4

---

schema/bom-1.5.schema.json

fix `vulnerability.affects[].versions[].range` ref

---

schema/bom-1.1.xsd
schema/bom-1.2-strict.schema.json
schema/bom-1.2.schema.json
schema/bom-1.2.xsd
schema/bom-1.3-strict.schema.json
schema/bom-1.3.schema.json
schema/bom-1.3.xsd

schema: own type for `ref`/`bom-ref`

---

tools/src/test/resources/1.5/valid-bom-1.5.json
tools/src/test/resources/1.5/valid-release-notes-1.5.json
tools/src/test/resources/1.5/valid-service-1.5.json

v1.5 fixed test data

---

schema/bom-1.5.proto
schema/bom-1.5.xsd

see https://github.com/CycloneDX/specification/issues/154#issuecomment-1399618819
fixes #154

streamline VulnerabilityReference

---

tools/src/test/resources/1.1/invalid-license-id-count-1.1.xml
tools/src/test/resources/1.2/invalid-license-id-count-1.2.xml
tools/src/test/resources/1.3/invalid-license-id-count-1.3.xml
tools/src/test/resources/1.4/invalid-license-id-count-1.4.xml
tools/src/test/resources/1.5/invalid-license-id-count-1.5.xml

Fix test data regarding invalid SPDX license ID

---

schema/bom-1.6.schema.json
tools/src/test/js/json-schema-lint-tests.js

Refactored JSON enum descriptions to use meta:enum

---

tools/src/test/resources/1.6/valid-bom-1.6.json
tools/src/test/resources/1.6/valid-bom-1.6.textproto

tests: add example for component scope

---

schema/bom-1.6.schema.json

docs: Spelling and grammar checks

---

schema/bom-1.6.schema.json

remove restriction on json's  `$schema` annotation

---

.github/dependabot.yml
.github/workflows/build_docs.yml
docgen/json/gen.sh
docgen/json/requirements.txt
docgen/xml/gen.sh
tools/src/test/proto/test.sh

- add dependabot for all used ecosystems
- revisit doc gen scripts to make dependencies maintainable more easily
followup: use a later/modern version of `Saxon-HE`

chore: depedabot for all used ecosystems

---

schema/bom-1.6.xsd

streamline typo fixes from  #451

issue451-streamline

---

schema/bom-1.6.proto
schema/bom-1.6.schema.json
schema/bom-1.6.xsd

pulled JSON docs over to XML and PB

[DOCS] 1.6 ecma takeover descriptions

---

schema/bom-1.6.proto
schema/bom-1.6.schema.json
schema/bom-1.6.xsd

1.6 ecma -- docs carry over

---

schema/bom-1.6.proto
schema/bom-1.6.schema.json
schema/bom-1.6.xsd

final change of milestone 1.6.1 -- see https://github.com/CycloneDX/specification/milestone/11

chore: prep v1.6.1

---

README.md

to mimic style from website https://cyclonedx.org/specification/overview/

docs: align media types in table

---

docgen/json/gen.sh
docgen/xml/gen.sh

docs: docsgen resture output for website

---

.github/pull_request_template.md

improve pull request template
- add info regarding processes
- add example regarding typo/spelling/grammar fix.

pull_request_template tell about rules

---

schema/bom-1.4.proto
schema/bom-1.4.schema.json
schema/bom-1.4.xsd
schema/bom-1.5.proto
schema/bom-1.5.schema.json
schema/bom-1.5.xsd
schema/bom-1.6.proto
schema/bom-1.6.schema.json
schema/bom-1.6.xsd

fix the URL to the version range spec (VERS) 
fixes #184
supersedes #187
closes #187

fix: version range spec url

---

README.md

docs: modernize build workflow badges

---

.github/ISSUE_TEMPLATE/1-feature.md
.github/ISSUE_TEMPLATE/2-defect.md
.github/ISSUE_TEMPLATE/config.yml

Also trim trailing whitespace, while at it.

Improve wording of issue templates

---

schema/bom-1.7.schema.json

It looks like we missed some key changes from the `1.7-dev-cryptography` branch. This PR will put them back in. Thanks @JoeyLupo for pointing that out!

Add missing changes 
